version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres 
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=hotel_booking
      - DB_SSLMODE=disable
      - SERVER_PORT=8080
      - JWT_SECRET=your_secret_key_replace_this_in_production
      - JWT_TOKEN_EXPIRY_HOURS=24
    restart: unless-stopped

  migrate:
    build:
      context: .
    entrypoint: [ "/usr/bin/migrate" ]
    command:
      - "-path=/app/migrations"
      - "-database=postgres://postgres:postgres@postgres:5432/hotel_booking?sslmode=disable"
      - "up"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_booking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: